---
# tasks file for home_dummy

- name: Creat a directory inside home called dummy
  ansible.builtin.file:
    path: ~/
    state: directory
    mode: '0755'


## create a directory based on the name_value, if it is already there, do not create it
## if you create then the change is true if you do not create then the change is false